FROM php:8.2-apache

# Install system deps
RUN apt-get update && apt-get install -y \
    git unzip libicu-dev libzip-dev zip libpq-dev \
    && docker-php-ext-install intl pdo pdo_pgsql zip

# Enable Apache mod_rewrite
RUN a2enmod rewrite

# Set working dir
WORKDIR /var/www/html

# Copy everything
COPY . .

# Set Apache DocumentRoot to /public
RUN sed -i 's|DocumentRoot /var/www/html|DocumentRoot /var/www/html/public|g' /etc/apache2/sites-available/000-default.conf

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer

# Install PHP dependencies
RUN composer install --no-dev --optimize-autoloader --no-interaction

# Set environment
ENV APP_ENV=prod

# Expose Apache port
EXPOSE 80
